### ISSUE TITLE
翻页后被删除楼层导致爬取中断 | 爬取不完全

### ISSUE THREAD

**Issue by xipingguo456** [Sorceresssis/TiebaScraper#1]
**中断**
id: 2267343048
报错如下：

正在爬取第 19 楼, pid = 32085081482
第2页爬取完成, 共5页, 每页30个帖子
正在爬取第 22 楼, pid = 32085081482
Traceback (most recent call last):
  File "E:\teiba\TiebaScraper-main\src\main.py", line 11, in <module>
    main()
  File "E:\teiba\TiebaScraper-main\src\main.py", line 7, in main
    asyncio.run(scrape(tid))
  File "C:\Users\12438\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\12438\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\12438\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "E:\teiba\TiebaScraper-main\src\scrape.py", line 59, in scrape
    await thread_servie.scrape()
  File "E:\teiba\TiebaScraper-main\src\services\thread_service.py", line 57, in scrape
    await self.save_post(post)
  File "E:\teiba\TiebaScraper-main\src\services\thread_service.py", line 146, in save_post
    self.post_dao.insert(
  File "E:\teiba\TiebaScraper-main\src\dao\post_dao.py", line 14, in insert
    self.db.execute(
sqlite3.IntegrityError: UNIQUE constraint failed: post.id

**不完全**
id: 2428664072
无报错，但只爬取至102楼，之后的楼层没有爬取。

**其他**（影响不大，也可能是我的问题）
使用TiebaReader阅读2428664072时，每一页会比网页版百度贴吧多一楼。

**Comment by Sorceresssis** [comment]
2267343048 的错误是是因为请求到数据有重复导致的 (贴吧早期对帖子的删除处理的不是很好)。重复的帖子再保存时触发了数据库的 Unique Constraint (唯一约束)，最新版已经修复。

还有一个项目本身的问题，就是不管什么帖子爬取都会少最后一页😂。现在已经修复了。

2428664072 的问题不好解决。要等待一段时间。

TiebaReader 的每页的楼数这不是错误。只是显示的个数不同。如果这个影响很大的话。我后续会给TiebaReader 添加可以设置每页显示多少楼的功能。

**Comment by Sorceresssis** [comment]
@xipingguo456 你试一下最新版的。注意要重新看一下 readme.md 安装依赖的操作有改变。
